### ISSUE TITLE
Can I test on single image or video?

### ISSUE THREAD

**Issue by woo1** [syguan96/DynaBOA#1]
Hi, Thanks for sharing this code
Can I test on single image or video by using this code?
run_on_3dpw.sh tests on various data, can you give me some guide to do this?

**Comment by syguan96** [comment]
For Q1, in our work, we focus on streaming images, which have temporal correlations. Therefore, you can test DynaBOA on videos. But for shuffled images, maybe you should remove temporal constraints first.

For Q2, I will update the code this week.

**Comment by woo1** [comment]
Thanks for your kind reply

**Comment by AK391** [comment]
@syguan96 can you please add a google colab for inference thanks

**Comment by syguan96** [comment]
@woo1, I added a guideline to run DynaBOA on internet videos. Please see readme for more details.

**Comment by syguan96** [comment]
@AK391 thanks for your interest. Following the guidance in readme step by step, you can learn how to infer results. I'd like to add a google colab, but I'm a little busy now.

**Comment by woo1** [comment]
@syguan96 
Thanks for your reply, it works well!
