### ISSUE TITLE
Question about Results on Internet Videos

### ISSUE THREAD

**Issue by Bin-Ji** [syguan96/DynaBOA#10]
Thanks for your great work!
When I try to run on internet videos, the 'imgname' in "h36m_random_sample_center_10_10.pt" is needed. However I extract the images of h36m by "python process_data.py --dataset h36m" and it doesn't match with the "imgname' above. Do I need to change the line 69 in "human36m.py" and get all the images?

**Comment by syguan96** [comment]
`h36m_random_sample_center_10_10.pt` has been uploaded. Please see readme for the download link.
