### ISSUE TITLE
3DPW

### ISSUE THREAD

**Issue by mahsaep** [syguan96/DynaBOA#11]
Hi and thanks for releasing the code!

I was wondering how the .npz files in the data_extras are generated? Is the 'smpl_j2d' used in adaptation part for 3DPW, the ground truth 2d keypoints or is it obtained from the Alphapose? If the former, does it mean that during adaptation on test domain on 3DPW, GT 2d keypoints are used?

Cheers!

**Comment by syguan96** [comment]
Hi Mahsa, thanks for your interest!  I use the GT 2D keypoints, same as other cross-dataset generalization works, e.g., ISO (Inference Stage Optimization for Cross-scenario 3D Human Pose Estimation). But for the demo on the internet video, I use 2D keypoint detected by Alphapose. You can refer to [this file](https://github.com/syguan96/BOA/blob/main/utils/data_preprocess/pw3d_process.py) for more details of processing 3DPW.

**Comment by mahsaep** [comment]
Thanks Shanyan for the speedy reply! 
I was wondenring how dynaBOA performs using Alphapose on 3DPW instead of GT. Have you investigate that in your work?
Thanks!

**Comment by syguan96** [comment]
Sorry, I didn't try this setting.

**Comment by syguan96** [comment]
After finishing a DDL, I will do a comparison.

**Comment by mahsaep** [comment]
thanks! would be great!

**Comment by mahsaep** [comment]
Hi Shanyan,

I checked the preprocessing of 3DPW from the BOA repo and I realized that 3DPW npz files are generated with keys being {imgname, center, scale, pose, shape, part, gender, smpl_j3d, smpl_j2d}. However, when loading from 3DPW in DynaBOA repo, the loaded keys are {imgname, scale, center, pose, shape, j2d, opj2d} which does not match the preprocessing code. I was wondering if you could please let me know if there is a different script for generating 3dpw npz files or let me know how opj2d are generated and saved in these files.

Thanks!

**Comment by mahsaep** [comment]
Could you please let me know what the opj2d is in the 3DPW npz files? is it the 2d keypoint obtained from openpose?

Cheers!

**Comment by syguan96** [comment]
Sorry for the late reply! `op_j2d ` is the 2D keypoints annotated in the original dataset. The data processing code should be released at the end of this month.

**Comment by syguan96** [comment]
Hi @mahsaep,  the script has been uploaded.
