### ISSUE TITLE
How's the optimization speed runtime?

### ISSUE THREAD

**Issue by lucasjinreal** [syguan96/DynaBOA#12]
For single person, how long it takes to optimized a proper result?

**Comment by syguan96** [comment]
Hi, you can refer to this [issue](https://github.com/syguan96/DynaBOA/issues/7#issuecomment-976372717)

**Comment by lucasjinreal** [comment]
@syguan96 Hi.

I calculated that would be about 1.5s / img? 
that's quit slow then..

BTW, for batchsize 32, how long will it takes? I suppose this for while optimize loop can be faster if larger batchsize.

But if assume 1.5s / img, that would be about 32s for bs=32? OMG..

**Comment by syguan96** [comment]
how do u calculate the time cost？on 3080， it takes 0.5s per image on 3dpw during training， including load data， forward/backward， logging etc. 

for faster speed，smaller network， multiprocessing， efficient image processing (crop, resize) or more efficient retrieval are promising points. any pr is welcome ：）

i don’t know what exactly you did
 when batchsize = 32. In all my experiments, only one target sample with retrieved source samples to be input to the network.

**Comment by lucasjinreal** [comment]
@syguan96 https://github.com/syguan96/DynaBOA/issues/7#issuecomment-976372717

> I remember it takes 15h roughly on the 3DPW test set (35515 images) with 3080 GPU.

Did u tested only infer time on single image with single person? if 500ms per image, including optimization and get final result, that would be very good.  how about batchsize == 32 time?

**Comment by syguan96** [comment]
I didn't strictly calculate the time cost. For example,  I remember rendering is excluded when calculating the time cost, and some logging and immediate file saving operations are taken in consideration.

The time is too long, I cannot give you a precise answer. But I will check it after an approaching DDL (at the end of this month). Really appreciate your interest and patience.

**Comment by lucasjinreal** [comment]
@syguan96 thank u. if the time is not too large, its would be a good solution for offline high accurate 3d pose which including online optimization.

**Comment by syguan96** [comment]
Hi, I tested the runtime on 3DPW. For our paper, the runtime includes two parts: adaptation time and inference time. Below are detailed results.

Due to the dynamic update scheme, the adaptation time is not constant. The statistics of adaptation time:
Total images: 35515
Mean: 0.49 s
Std: 0.23 s
Max: 2.48 s
Min: 0.30 s
Num of images whose runtime is larger than 1s: 1439

The mean inference time is 0.01s.

Hope this can help you. We will add the discussion on runtime in the next update.

**Comment by lucasjinreal** [comment]
@syguan96 0.01s per img? that's 10ms , if. so then  seems great!!  0.3s ~ 1s adaptation time, why it was so large range?

**Comment by syguan96** [comment]
Nope, for each image, we will adapt the model first, and then we conduct inference by the adapted model. So, the average runtime is 0.5s. To accelerate it, maybe adapting the model every 3 images?

**Comment by syguan96** [comment]
We design a dynamic update scheme for some hard examples (refer to Fig. 7). Specifically, we additionally adapt the model with several times according to the feature distance.  Some extremely hard samples will be updated up to 7 times. But for some regular frame, the model will only be bilevel updated one time.

**Comment by lucasjinreal** [comment]
@syguan96 have u tested on some internet videos, how long will it takes go though all video frames? in one video, the scenes could be very similar, the time might be smooth and stable .
