### ISSUE TITLE
Stuck while testing

### ISSUE THREAD

**Issue by DingYikang** [syguan96/DynaBOA#16]
Hi,

Thanks for your nice work. I'm facing a strange problem that the program is stuck when test on internet data. It looks like:
![image](https://user-images.githubusercontent.com/58066278/155837195-918665a7-7f06-4f24-a8b7-9983e909b7e5.png)

And I find the GPU-utilization is nearly 0. Is the procedure still going on normally? How long should it take when test on internet data?
![image](https://user-images.githubusercontent.com/58066278/155837383-82119d56-d5e9-4b32-a571-29ca245d4f3d.png)

Looking forward to your reply!

**Comment by syguan96** [comment]
Have you solved this problem?

**Comment by ChawDoe** [comment]
> Hi,
> 
> Thanks for your nice work. I'm facing a strange problem that the program is stuck when test on internet data. It looks like: ![image](https://user-images.githubusercontent.com/58066278/155837195-918665a7-7f06-4f24-a8b7-9983e909b7e5.png)
> 
> And I find the GPU-utilization is nearly 0. Is the procedure still going on normally? How long should it take when test on internet data? ![image](https://user-images.githubusercontent.com/58066278/155837383-82119d56-d5e9-4b32-a571-29ca245d4f3d.png)
> 
> Looking forward to your reply!

Hey, I met the same problem. Any idea about it?
