### ISSUE TITLE
Rersults on internet data when use alphapose26

### ISSUE THREAD

**Issue by DingYikang** [syguan96/DynaBOA#17]
Hi,

Thanks for your nice work! Recently, I'm tring to use DynaBOA on internet data with alphapose-26 pose. I didn't see such 26 key points configs in kp_utils.py. So I'm wondering can DynaBOA support alphapose-26 pose now? How can I use alphapose-26 pose on internet data?

Thanks and looking forward to your reply~

**Comment by syguan96** [comment]
Could you please tell me the order of the 26 keypoints?
