### ISSUE TITLE
"h36m_part.h5" missed

### ISSUE THREAD

**Issue by MooreManor** [syguan96/DynaBOA#2]
Hello. Thanks for your excellent job.
I met an error while running your code. It seemed that I missed this file "h36m_part.h5". Where can I get this file?
`
File "dynaboa.py", line 94, in __init__
`
`
          fin = h5py.File('/dev/shm/h36m_part.h5', 'r')
`

**Comment by MooreManor** [comment]
Besides, will you offer a demo program to run on videos in the future?

**Comment by syguan96** [comment]
Thanks for your interest. I update the readme and the code just now. You can additionally download [this file](https://drive.google.com/file/d/1uekfFsWnLcKdrT6CxZ9zFQFy_ySdDaXK/view?usp=sharing) and Human 3.6M to try our DynaBOA.

I will release the code running on the demo videos soon.

**Comment by MooreManor** [comment]
Thank you for the detailed answer!

**Comment by MooreManor** [comment]
Thanks for your reply.
I think that the missed file is "h36m_part.h5", but the upper link given is"h36m_random_sample_center_10_10.pt". 
Can you share the file "h36m_part.h5" or preprocessed file to change h36m to "h36m_part.h5"? Thanks.

**Comment by syguan96** [comment]
I'd like to share `h36m_part.h5`. But this file is too large. My google drive doesn't have enough space to share it. By downloading `h36m_random_sample_center_10_10.pt` and Human 3.6M, you can also run DynaBOA.

In fact, the only difference between the two choices is that we offline crop the images of Human 3.6M and save them into `h36m_part.h5`.

**Comment by MooreManor** [comment]
Thanks a lot for your prompt reply!

**Comment by MooreManor** [comment]
https://github.com/syguan96/DynaBOA/blob/368a10a0f2d2eb79bd11bc638bc454c11c544e33/boa_dataset/pw3d.py#L34
If [data](https://drive.google.com/file/d/1_4GhHaiNIu2aidVwMBvbdcdGd2vgy-gR/view?usp=sharing) is used, this path should be changed to `self.pw3d_datas = glob.glob('data/data_extras/3dpw_[0-9]*_[0-9].npz')`.

https://github.com/syguan96/DynaBOA/blob/368a10a0f2d2eb79bd11bc638bc454c11c544e33/config.py#L7
And this line should be noticed to change according to your own 3dpw path.

Besides, [data](https://drive.google.com/file/d/1_4GhHaiNIu2aidVwMBvbdcdGd2vgy-gR/view?usp=sharing) seem to lose directory `spin_data` [spin_data](https://smplify.is.tue.mpg.de/).

**Comment by MooreManor** [comment]
And could you share the preprocess file to change raw h36m videos to the images? Thanks.

**Comment by syguan96** [comment]
Thanks for your detailed comments! To process Human 3.6M, you can refer to [this script](https://github.com/syguan96/BOA/blob/main/utils/data_preprocess/human36m.py).

**Comment by MooreManor** [comment]
Thanks for your patient reply :)

**Comment by syguan96** [comment]
I update my repo with more detailed instructions to process Human 3.6M. @MooreManor

**Comment by MooreManor** [comment]
Thanks! I'll take a try.
