### ISSUE TITLE
how to use OpenPose  to replace alphapose

### ISSUE THREAD

**Issue by aigoruan** [syguan96/DynaBOA#22]
hi, when I want to use openpose to detect 2d pose, I found it will check keypoints number by 17 ? And it seem not adapt for openpose in the code.

**Comment by syguan96** [comment]
The estimated joint names are:
```
JOINT_NAMES = [
# 25 OpenPose joints (in the order provided by OpenPose)
'OP Nose',
'OP Neck',
'OP RShoulder',
'OP RElbow',
'OP RWrist',
'OP LShoulder',
'OP LElbow',
'OP LWrist',
'OP MidHip',
'OP RHip',
'OP RKnee',
'OP RAnkle',
'OP LHip',
'OP LKnee',
'OP LAnkle',
'OP REye',
'OP LEye',
'OP REar',
'OP LEar',
'OP LBigToe',
'OP LSmallToe',
'OP LHeel',
'OP RBigToe',
'OP RSmallToe',
'OP RHeel',
# 24 Ground Truth joints (superset of joints from different datasets)
'Right Ankle',      # 25, 0
'Right Knee',       # 26, 1
'Right Hip',        # 27, 2
'Left Hip',         # 28, 3
'Left Knee',        # 29, 4
'Left Ankle',       # 30, 5
'Right Wrist',      # 31, 6
'Right Elbow',      # 32, 7
'Right Shoulder',   # 33, 8
'Left Shoulder',    # 34, 9
'Left Elbow',       # 35, 10
'Left Wrist',       # 36, 11
'Neck (LSP)',       # 37, 12 ###
'Top of Head (LSP)',# 38, 13
'Pelvis (MPII)',    # 39, 14 #
'Thorax (MPII)',    # 40, 15
'Spine (H36M)',     # 41, 16 #
'Jaw (H36M)',       # 42, 17 #
'Head (H36M)',      # 43, 18 #
'Nose',             # 44, 19
'Left Eye',         # 45, 20
'Right Eye',        # 46, 21
'Left Ear',         # 47, 22
'Right Ear'         # 48, 23
]
```

You can use the first 25 joints to calculate 2D keypoint loss.

**Comment by aigoruan** [comment]
I followed your steps to run this project without human 3.6M with some doubts:
1. gmm_08.pkl file should be place in data/spin_data ? 
2. after alphapose detect 2d pose, the json file must be rename for seq*_*.json?
3. if run internet video, when do we need multiple json files that will be processed in internet_data.py ?

**Comment by syguan96** [comment]
1. No, just place `gmm_08.pkl` into the `data` folder.
2. It is not necessary. Just make sure the JSON files can be found. Change this line as your will.
https://github.com/syguan96/DynaBOA/blob/622e4e27bb31e084e7657fee5eebf788d0b102b3/utils/data_preprocess/internet_data.py#L46
3. If you only test on one video, there is one json file to be processed.
