### ISSUE TITLE
[Paper] Definition of 'Online Adaption'

### ISSUE THREAD

**Issue by vivi90** [syguan96/DynaBOA#23]
I have taken a look at your paper but i am still not sure, what you exactly mean by 'Online Adaption'.

**Comment by syguan96** [comment]
For streaming data, adaptation scheme has two   branches： 1) offline. When an new images coming, the optimization start from the source model; 2) Online. Compared to the offline manner, online optimization start from the model which is adapted on the previous image. The qualitative comparison is shown in our project page. 

From my phone

**Comment by vivi90** [comment]
> [..] 
> 1) offline. When an new images coming, the optimization start from the source model; 
> 2) Online. Compared to the offline manner, online optimization start from the model which is adapted on the previous image.

Ah, i see.
Thank you, very much! 🙂 

*Btw, might be good to add this to the README file.*
