### ISSUE TITLE
error Running on the 3DPW 

### ISSUE THREAD

**Issue by CapenZen** [syguan96/DynaBOA#27]
Make some error when I run bash run_on_3dpw.sh

root@ubuntu:~/DYNABOA/DynaBOA# bash run_on_3dpw.sh
  File "dynaboa_benchmark.py", line 101
    print(f'Step:{self.global_step}: MPJPE:{np.mean(mpjpe_all)}, PAMPJPE:{np.mean(pampjpe_all)}, PVE:{np.mean(pve_all)}')
                                                                                                                       ^
SyntaxError: invalid syntax

**Comment by syguan96** [comment]
Please assert `import ipdb;ipdb.set_trace()` to analyze what happend.
