### ISSUE TITLE
.yaml file

### ISSUE THREAD

**Issue by farzammpm** [syguan96/DynaBOA#3]
Hello, Interesting job. Congratulation. I have been trying to run your code on my system, how ever the .yaml export file is platform specific. And many difficulties will arise trying to download and install packages on different systems. It would be so nice if you could export it in a cross platform manner and also would appreciate much more if you could export using .txt . anaconda has some bugs updating environments in .yaml format. It downloads everything from scratch every time you try to update your environment using .yaml format. I managed to read and install your packages using a code i wrote in VScode . However i thought it worth to mention. Best regards.

**Comment by syguan96** [comment]
Thank you for your reminder! I will change it to requirements.txt right now.

**Comment by syguan96** [comment]
@farzammpm could you please check the update?

**Comment by farzammpm** [comment]
hi, thank you for quick reply. i tested it, and it is much better. thanks :)
