### ISSUE TITLE
File generation under the data/retrieval_res folder

### ISSUE THREAD

**Issue by sigma-alpha-beta** [syguan96/DynaBOA#30]
Thanks for your great work, I want to know how the files in the 'data/retrieval_res' folder are generated. Could you share the scripts that generate these files? thanks

**Comment by syguan96** [comment]
Thanks for your interest! I will upload it soon.

**Comment by syguan96** [comment]
I am a little busy now. If you need it urgently, I can give the dirty code to your email.

**Comment by sigma-alpha-beta** [comment]
> I am a little busy now. If you need it urgently, I can give the dirty code to your email.

thanks for your reply, my email is guoguangchao@126.com, thanks a lot
