### ISSUE TITLE
Takes too much time inferencing 3DPW

### ISSUE THREAD

**Issue by dqj5182** [syguan96/DynaBOA#36]
Hi.
I am now running inference for 3DPW dataset, but having trouble with inference time.
When I run run_on_3dpw.sh, the 3DPW inference time is about 17 hours which is quite a long time.
Is this normal? or am I missing something?
<img width="668" alt="Screen Shot 2022-12-22 at 2 04 53 PM" src="https://user-images.githubusercontent.com/56655511/209061247-d6e3e1e9-96af-49d3-93b1-44dfd0a67c5d.png">

**Comment by syguan96** [comment]
Hi,
It takes less time in my environment. But the code indeed is slow, since the model is fine-tuned on every test image.

From my phone

**Comment by dqj5182** [comment]
Hi.

Thank you for your comment!
After running second validation experiment, the experiment took about 8 hours. Nice to know that this is not just my problem!

Always thanks for your quick response.
