### ISSUE TITLE
About pre-trained basemodel.pt of multiple datasets

### ISSUE THREAD

**Issue by dqj5182** [syguan96/DynaBOA#38]
Do you have pre-trained HMR checkpoint like basemodel.pt but pre-trained on same multiple datasets (MPI-INF-3DHP, LSPET, ...)?

**Comment by syguan96** [comment]
Sorry, I didn't train the base-model under this setting. One possible solution is loading the pre-trained HMR checkpoint and finetuning it since we use GroupNorm instead of BN.
