### ISSUE TITLE
About real-time, multiplayer

### ISSUE THREAD

**Issue by zhanghongyong123456** [syguan96/DynaBOA#7]
1. fps  4k
2. I saw that the demo is all solo. Can multiple people do it

**Comment by syguan96** [comment]
If I understand Q1 correctly, you want to know the fps of DynaBOA. 
For Q1, I haven't strictly calculated the fps of DynaBOA after deployment.  There are many factors that affect the running time. I didn't specifically optimize my code. For the current implementation, I remember it takes 15h roughly on the 3DPW test set (35515 images) with 3080 GPU.

For Q2, refer to VIBE, you can regress 3D mesh for each people and then render them together. It's a little bit tricky. How to dig the correlation between multiply people to further improve the adaptation results is a promising direction.

**Comment by zhanghongyong123456** [comment]
> If I understand Q1 correctly, you want to know the fps of DynaBOA. For Q1, I haven't strictly calculated the fps of DynaBOA after deployment. There are many factors that affect the running time. I didn't specifically optimize my code. For the current implementation, I remember it takes 15h roughly on the 3DPW test set (35515 images) with 3080 GPU.
> 
> For Q2, refer to VIBE/ROMP, you can regress 3D mesh for each people and then render them together. It's a little bit tricky. How to dig the correlation between multiply people to further improve the adaptation results is a promising direction.

Yes, thank you very much for your reply.thank you for such an excellent work
