### ISSUE TITLE
Missing file: spin_data->gmm_08.pkl

### ISSUE THREAD

**Issue by Bilgee** [syguan96/DynaBOA#8]
Thank you for your great work. 
I tested your code using 3DPW dataset. I unzipped File1 into "data" but there was missing file : spin_data gmm_08.pkl
Can you upload it?

**Comment by syguan96** [comment]
Thanks for your reminder! You can download `gmm_08.pkl` from this [URL](https://drive.google.com/file/d/1q2e0rwpWdOmXc54qOErJMxZZDJYEJisw/view?usp=sharing).
